version: "3.9"

services:
  app:
    build: .
    ports:
      - "8000:8000"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: project_x
    ports:
      - "5432:5432"
